# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='symptomtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
