# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(to='Medic_App.Symptom'),
        ),
    ]
