# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medic_App', '0002_auto_20160405_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='commonness',
            field=models.CharField(choices=[(1, 'very uncommon'), (2, 'uncommon'), (3, 'common'), (4, 'very common')], max_length=30),
        ),
    ]
